### ISSUE TITLE
ModuleNotFoundError: No module named '_envcpp'

### ISSUE THREAD

**Issue by AdithyaRaman** [thu-media/Comyco#8]
When running `python train.py` I am hit with the error that says there is no _envcpp module

```
WARNING:tensorflow:From /home/adithya/miniconda3/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "/home/adithya/ub/ub/research/Comyco/src/envcpp.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/adithya/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_envcpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adithya/ub/ub/research/Comyco/src/train.py", line 6, in <module>
    import envcpp as env
  File "/home/adithya/ub/ub/research/Comyco/src/envcpp.py", line 17, in <module>
    _envcpp = swig_import_helper()
  File "/home/adithya/ub/ub/research/Comyco/src/envcpp.py", line 16, in swig_import_helper
    return importlib.import_module('_envcpp')
  File "/home/adithya/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_envcpp'

```

**Comment by godka** [comment]
Sorry for the long delay, have you ever compiled the instant solver?

```

swig -c++ -python abr.i

g++ abr_wrap.cxx env.cpp -fPIC -shared -I /usr/include/python2.7/ -L /usr/lib/python2.7 -o _envcpp.so -O4

```

**Comment by fcbw2012** [comment]
> Sorry for the long delay, have you ever compiled the instant solver?
> 
> ```
> 
> swig -c++ -python abr.i
> 
> g++ abr_wrap.cxx env.cpp -fPIC -shared -I /usr/include/python2.7/ -L /usr/lib/python2.7 -o _envcpp.so -O4
> ```

你好，我也遇到了相同的问题。请问是需要在运行train.py之前要编译instant solver吗？但是在src目录下已经存在envcpp.py文件了。只是想测试下instant solver的输出，会有如下报错。请问该怎样解决呢？如果要重新编译instant solver，该怎样编译呢？感谢！
`Traceback (most recent call last):
  File "D:\BUPT\Python_learning\tensorflow_test\Comyco-master\src\envcpp.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing _envcpp: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/BUPT/Python_learning/tensorflow_test/Comyco-master/src/train.py", line 4, in <module>
    import envcpp as env
  File "D:\BUPT\Python_learning\tensorflow_test\Comyco-master\src\envcpp.py", line 17, in <module>
    _envcpp = swig_import_helper()
  File "D:\BUPT\Python_learning\tensorflow_test\Comyco-master\src\envcpp.py", line 16, in swig_import_helper
    return importlib.import_module('_envcpp')
  File "D:\anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _envcpp: 找不到指定的模块。

Process finished with exit code 1
`

**Comment by godka** [comment]
please check whether the file "_envcpp.pyd" is available if you use the windows version.
